server/api/cats.js, server/api/index.js, server/api/products.js, server/api/users.js, server/db/index.js
=> 10 express routes

client/components/products.js, client/store/product.js, client/store/singleProduct.js, client/store/store.js, client/store/updateProduct.js, server/api/cats.js, server/api/products.js, server/api/users.js
=> 9 react component

README.md
=> Feature: Front end design

client/components/navbar.js, client/routes.js, server/api/cart.js
=> Chore: connect admin view

client/store/cart.js
=> 19-cart-redux

client/routes.js
=> 48-admin-route merge

client/components/Cats.js, client/components/NewCat.js, client/components/RemoveCat.js, client/components/UpdateCat.js, client/components/admin.js, client/components/navbar.js, client/components/user-home.js, client/routes.js, server/api/cats.js, server/auth/google.js, server/index.js
=> Chore: Admin complete

client/app.js, client/components/Cats.js, client/components/cart.js, client/routes.js, client/store/cart.js, client/store/index.js, public/style.css, script/seed.js, server/api/cart.js, server/auth/google.js, server/index.js
=> 17-cart-updates

client/components/RemoveCat.js, client/components/UpdateCat.js, client/store/singleCat.js, script/seed.js, server/api/cats.js
=> 18-debug done

client/components/cart.js, client/store/cart.js, server/api/cart.js
=> feature:checkout button

client/components/NewCat.js, client/components/UpdateCat.js, client/components/navbar.js
=> Chore: Front end design

client/components/auth-form.js, client/components/cart.js, client/store/user.js, package-lock.json, package.json, server/api/users.spec.js, server/db/models/user.js, server/index.js, webpack.config.js
=> Signup page

client/components/admin.js, server/index.js
=> Chore: remove edit and delete buttons from user

client/components/Cats.js, client/components/SingleCat.js, client/components/cart.js, client/components/navbar.js, client/routes.js, client/store/cart.js, client/store/singleCat.js, server/api/cart.js, server/api/cats.js
=> Removing consolelogs

client/components/cart.js, public/style.css
=> 14-cart-updat

client/app.js, client/components/Cats.js, client/components/auth-form.js, client/components/cart.js, client/components/guestCartFxns.js, client/components/navbar.js, client/routes.js, client/store/cart.js, client/store/cat.js, client/store/singleCat.js, client/store/user.js, package-lock.json, package.json, script/seed.js, server/api/users.spec.js
=> 89 90 user login admin auth

client/app.js, client/components/Account.js, client/components/Cats.js, client/components/UpdateCat.js, client/components/cart.js, client/components/navbar.js, client/index.js, client/routes.js, client/store/user.js, package-lock.json, package.json, public/style.css, server/api/cats.js, server/api/gatekeeper.js, server/api/users.js, server/index.js
=> 78 user self edit

client/components/cart.js, client/components/guestCartFxns.js, client/components/user-home.js, client/store/cart.js, package-lock.json, package.json, server/api/cart.js, server/api/users.spec.js, server/index.js
=> 76 guest cart

client/components/cart.js, package-lock.json, package.json, server/api/checkout.js
=> 79 stripe database

README.md, client/components/navbar.js
=> 79 order nav bar

server/auth/google.js
=> fix:google oauth account no longer admin
